-- ============================================================
-- gbrain · Phase 0 · Foundation migration
-- Run in Supabase SQL Editor (or psql against the direct
-- connection). Idempotent — safe to re-run.
-- ============================================================

-- ── extensions ──────────────────────────────────────────────
create extension if not exists vector;      -- pgvector (storage only — embeddings generated by a worker)
create extension if not exists pg_trgm;     -- fuzzy matching (identity resolution, Phase 4)
create extension if not exists pgmq cascade;-- durable queues

-- ============================================================
-- ‼ DECISION (RESOLVED): embeddings = Gemini Embedding on Vertex AI,
--   MRL-truncated to 768 dims. Best-in-class retrieval, ~free against
--   Vertex credits. Generated by a batched embed worker; Supabase
--   stores the vectors only. 768 also fits text-embedding-005 (native),
--   the simpler same-cost fallback, and Voyage voyage-4 if avoiding
--   Google. embed_model per chunk → a future swap is selective.
-- ============================================================

-- ── 1. BRONZE: immutable raw landing ────────────────────────
create table if not exists gb_raw (
  id            uuid primary key default gen_random_uuid(),
  source        text not null,             -- whatsapp|gmail|calendar|drive_doc|pdf|dashboard|test
  source_id     text not null,             -- native id (message id, gmail id, event id…)
  payload       jsonb not null,            -- verbatim webhook / API body
  storage_ref   text,                      -- Supabase Storage path for binary/original file
  content_hash  text,                      -- sha256 of canonical content (filled at normalize if absent)
  received_at   timestamptz not null default now(),
  unique (source, source_id)               -- native-id dedup at the door (absorbs Whapi/Gmail retries)
);

-- ── 2. SILVER: canonical envelope ───────────────────────────
create table if not exists gb_envelope (
  id              uuid primary key default gen_random_uuid(),
  raw_id          uuid references gb_raw(id),
  idempotency_key text not null unique,    -- sha256(source+native_id+content_hash) — kills cross-channel dup
  source          text not null,
  source_id       text not null,
  kind            text not null,           -- message|email|event|document|file|record
  thread_id       text,
  occurred_at     timestamptz,
  ingested_at     timestamptz not null default now(),
  actors          jsonb default '{}',      -- {from, to[], participants[]}
  title           text,
  body_raw        text,
  body_clean      text,                    -- quotes/sigs/boilerplate stripped — fewer billed tokens
  signal_score    real default 0,
  labels          text[] default '{}',
  permissions     jsonb default '{}',      -- {acl[], visibility}
  provenance      jsonb default '{}',      -- {raw_ref, content_hash, sync_cursor}
  extraction      jsonb,                   -- LLM structured output (Phase 1)
  status          text not null default 'raw',
  skip_reason     text,                    -- why the gate killed it (dup|low_signal|unchanged)
  schema_version  int not null default 1,
  body_fts        tsvector generated always as (to_tsvector('english', coalesce(body_clean,''))) stored,
  constraint gb_env_status_chk check (status in
    ('raw','normalized','skipped','preprocessed','extracted','embedded','resolved','indexed','failed'))
);
create index if not exists gb_env_status_idx on gb_envelope(status);
create index if not exists gb_env_thread_idx on gb_envelope(thread_id);
create index if not exists gb_env_source_idx on gb_envelope(source, occurred_at);
create index if not exists gb_env_fts_idx    on gb_envelope using gin(body_fts);

-- ── attachments (hash-deduped, reference-once) ──────────────
create table if not exists gb_attachment (
  id           uuid primary key default gen_random_uuid(),
  envelope_id  uuid references gb_envelope(id),
  hash         text not null,              -- same deck via email+WA → one row
  mime         text,
  storage_ref  text,
  text_layer   boolean,                    -- true = skip OCR
  pages        int,
  unique (hash)                            -- the deck-dedup constraint
);

-- ── chunks (page-aware, citeable) ───────────────────────────
create table if not exists gb_chunk (
  id            uuid primary key default gen_random_uuid(),
  envelope_id   uuid references gb_envelope(id),
  attachment_id uuid references gb_attachment(id),
  seq           int not null,
  page          int,
  text          text not null,
  token_est     int,
  embedding     vector(768),               -- Gemini Embedding (Vertex), MRL-truncated. See header.
  embed_model   text,
  content_fts   tsvector generated always as (to_tsvector('english', text)) stored
);
create index if not exists gb_chunk_vec_idx on gb_chunk using hnsw (embedding vector_cosine_ops);
create index if not exists gb_chunk_fts_idx on gb_chunk using gin(content_fts);
create index if not exists gb_chunk_env_idx on gb_chunk(envelope_id);

-- ── entities & graph edges ──────────────────────────────────
create table if not exists gb_entity (
  id           uuid primary key default gen_random_uuid(),
  type         text not null,              -- person|company|deal|meeting|document|investor
  canonical    text not null,
  attrs        jsonb default '{}',
  keys         jsonb default '{}',         -- {phone, email, domain, deal_id} for deterministic matching
  unique (type, canonical)
);
create table if not exists gb_edge (
  id           uuid primary key default gen_random_uuid(),
  src          uuid references gb_entity(id),
  rel          text not null,              -- works_at|involves|mentions|attended|sent
  dst          uuid references gb_entity(id),
  envelope_id  uuid references gb_envelope(id),
  occurred_at  timestamptz,
  unique (src, rel, dst, envelope_id)
);

-- ── sync cursors (per source) ───────────────────────────────
create table if not exists gb_sync_cursor (
  source       text primary key,           -- gmail|calendar|drive…
  cursor       jsonb not null,             -- {historyId} | {syncToken} | {pageToken}
  watch_expiry timestamptz,                -- renew BEFORE this
  updated_at   timestamptz default now()
);

-- ── batch tracking (Phase 1 consumers; tables ready now) ────
create table if not exists gb_batch (
  id           uuid primary key default gen_random_uuid(),
  kind         text not null,              -- extract|embed
  provider_id  text,                       -- Anthropic batch id
  status       text not null default 'submitted',
  item_count   int,
  submitted_at timestamptz default now(),
  completed_at timestamptz
);
create table if not exists gb_batch_item (
  batch_id     uuid references gb_batch(id),
  envelope_id  uuid references gb_envelope(id),
  custom_id    text,
  primary key (batch_id, custom_id)
);

-- ── cost log + dead-letter ──────────────────────────────────
create table if not exists gb_cost_log (
  id           uuid primary key default gen_random_uuid(),
  envelope_id  uuid,
  stage        text,                       -- extract|embed|resolve|serve
  model        text,
  tokens_in    int,
  tokens_out   int,
  cached_in    int,
  usd          numeric(10,5),
  at           timestamptz default now()
);
create table if not exists gb_dlq (
  id           uuid primary key default gen_random_uuid(),
  stage        text,
  envelope_id  uuid,
  payload      jsonb,
  error        text,
  retries      int default 0,
  at           timestamptz default now()
);

-- ── lock PostgREST access (workers connect as postgres role,
--    which bypasses RLS; anon/authenticated get nothing) ─────
alter table gb_raw         enable row level security;
alter table gb_envelope    enable row level security;
alter table gb_attachment  enable row level security;
alter table gb_chunk       enable row level security;
alter table gb_entity      enable row level security;
alter table gb_edge        enable row level security;
alter table gb_sync_cursor enable row level security;
alter table gb_batch       enable row level security;
alter table gb_batch_item  enable row level security;
alter table gb_cost_log    enable row level security;
alter table gb_dlq         enable row level security;

-- ── observability: one view answering "what's stuck?" ───────
create or replace view gb_pipeline_status as
select status,
       count(*)                          as items,
       min(ingested_at)                  as oldest,
       max(ingested_at)                  as newest
from gb_envelope
group by status
order by items desc;
